### ISSUE TITLE
https://nitro-azure-demo.nuxtjs.org HTTP ERROR 404

### ISSUE THREAD

**Issue by mvanolden** [nuxt/nitro-demo#30]
This nitro-azure-demo.nuxtjs.org page can’t be foundNo webpage was found for the web address: https://nitro-azure-demo.nuxtjs.org/
HTTP ERROR 404

**Comment by pi0** [comment]
Hi @mvanolden. Thanks for reporting it. I've moved it to #35. We will track it soon :)
